export const topMoviesAccion = [
  {
    Title: "Nobody",
    Year: "2021",
    Rated: "R",
    Released: "26 Mar 2021",
    Runtime: "92 min",
    Genre: "Action, Crime, Drama",
    Director: "Ilya Naishuller",
    Writer: "Derek Kolstad",
    Actors: "Bob Odenkirk, Aleksey Serebryakov, Connie Nielsen",
    Plot:
      "A bystander who intervenes to help a woman being harassed by a group of men becomes the target of a vengeful drug lord.",
    Language: "English, Russian, Spanish",
    Country: "United States, Japan",
    Awards: "2 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMjM5YTRlZmUtZGVmYi00ZjE2LWIyNzAtOWVhMDk1MDdkYzhjXkEyXkFqcGdeQXVyMjMxOTE0ODA@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "7.4/10" },
      { Source: "Rotten Tomatoes", Value: "84%" },
      { Source: "Metacritic", Value: "64/100" },
    ],
    Metascore: "64",
    imdbRating: "7.4",
    imdbVotes: "131,437",
    imdbID: "tt7888964",
    Type: "movie",
    DVD: "15 Apr 2021",
    BoxOffice: "$27,268,035",
    Production: "87North, Odenkirk Provissiero Entertainment, Eighty Two Films",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "RoboCop",
    Year: "1987",
    Rated: "R",
    Released: "17 Jul 1987",
    Runtime: "102 min",
    Genre: "Action, Crime, Sci-Fi",
    Director: "Paul Verhoeven",
    Writer: "Edward Neumeier, Michael Miner",
    Actors: "Peter Weller, Nancy Allen, Dan O'Herlihy",
    Plot:
      "In a dystopic and crime-ridden Detroit, a terminally wounded cop returns to the force as a powerful cyborg haunted by submerged memories.",
    Language: "English",
    Country: "United States",
    Awards: "Won 1 Oscar. 11 wins & 13 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZWVlYzU2ZjQtZmNkMi00OTc3LTkwZmYtZDVjNmY4OWFmZGJlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "7.5/10" },
      { Source: "Rotten Tomatoes", Value: "90%" },
      { Source: "Metacritic", Value: "67/100" },
    ],
    Metascore: "67",
    imdbRating: "7.5",
    imdbVotes: "239,644",
    imdbID: "tt0093870",
    Type: "movie",
    DVD: "27 Aug 2015",
    BoxOffice: "$53,424,681",
    Production: "Orion Pictures",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "John Wick",
    Year: "2014",
    Rated: "R",
    Released: "24 Oct 2014",
    Runtime: "101 min",
    Genre: "Action, Crime, Thriller",
    Director: "Chad Stahelski, David Leitch",
    Writer: "Derek Kolstad",
    Actors: "Keanu Reeves, Michael Nyqvist, Alfie Allen",
    Plot:
      "An ex-hit-man comes out of retirement to track down the gangsters that killed his dog and took everything from him.",
    Language: "English, Russian, Hungarian",
    Country: "United States, United Kingdom, China",
    Awards: "5 wins & 10 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTU2NjA1ODgzMF5BMl5BanBnXkFtZTgwMTM2MTI4MjE@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "7.4/10" },
      { Source: "Rotten Tomatoes", Value: "86%" },
      { Source: "Metacritic", Value: "68/100" },
    ],
    Metascore: "68",
    imdbRating: "7.4",
    imdbVotes: "564,409",
    imdbID: "tt2911666",
    Type: "movie",
    DVD: "07 Jun 2016",
    BoxOffice: "$43,037,835",
    Production: "Thunder Road Pictures, Defynite Films, 87eleven",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Matrix",
    Year: "1993",
    Rated: "N/A",
    Released: "01 Mar 1993",
    Runtime: "60 min",
    Genre: "Action, Drama, Fantasy",
    Director: "N/A",
    Writer: "Grenville Case",
    Actors: "Nick Mancuso, Phillip Jarrett, Carrie-Anne Moss",
    Plot:
      'Steven Matrix is one of the underworld\'s foremost hitmen until his luck runs out, and someone puts a contract out on him. Shot in the forehead by a .22 pistol, Matrix "dies" and finds himself in "The City In Between", where he is sho',
    Language: "English",
    Country: "Canada",
    Awards: "1 win",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BYzUzOTA5ZTMtMTdlZS00MmQ5LWFmNjEtMjE5MTczN2RjNjE3XkEyXkFqcGdeQXVyNTc2ODIyMzY@._V1_SX300.jpg",
    Ratings: [{ Source: "Internet Movie Database", Value: "7.9/10" }],
    Metascore: "N/A",
    imdbRating: "7.9",
    imdbVotes: "143",
    imdbID: "tt0106062",
    Type: "series",
    totalSeasons: "N/A",
    Response: "True",
  },
  {
    Title: "Depredador",
    Year: "2018",
    Rated: "N/A",
    Released: "17 Oct 2018",
    Runtime: "N/A",
    Genre: "Short, Crime",
    Director: "Amos Ruiz",
    Writer: "Amos Ruiz",
    Actors: "Carlos Bravo, Esther Machín, Esther Machín, Laura Junquera",
    Plot: "N/A",
    Language: "Spanish",
    Country: "Spain",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BY2I2ZWI1NjctOTcwOS00YWU3LWFmZjYtNTY4NzgzYzNhMTEwXkEyXkFqcGdeQXVyOTkwNDExOTU@._V1_SX300.jpg",
    Ratings: [],
    Metascore: "N/A",
    imdbRating: "N/A",
    imdbVotes: "N/A",
    imdbID: "tt9795632",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Aliens",
    Year: "1986",
    Rated: "R",
    Released: "18 Jul 1986",
    Runtime: "137 min",
    Genre: "Action, Adventure, Sci-Fi",
    Director: "James Cameron",
    Writer: "James Cameron, David Giler, Walter Hill",
    Actors: "Sigourney Weaver, Michael Biehn, Carrie Henn",
    Plot:
      "Fifty-seven years after surviving an apocalyptic attack aboard her space vessel by merciless space creatures, Officer Ripley awakens from hyper-sleep and tries to warn anyone who will listen about the predators.",
    Language: "English",
    Country: "United Kingdom, United States",
    Awards: "Won 2 Oscars. 20 wins & 23 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZGU2OGY5ZTYtMWNhYy00NjZiLWI0NjUtZmNhY2JhNDRmODU3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "8.3/10" },
      { Source: "Rotten Tomatoes", Value: "97%" },
      { Source: "Metacritic", Value: "84/100" },
    ],
    Metascore: "84",
    imdbRating: "8.3",
    imdbVotes: "668,122",
    imdbID: "tt0090605",
    Type: "movie",
    DVD: "25 Nov 2015",
    BoxOffice: "$85,160,248",
    Production: "Twentieth Century Fox, Brandywine Productions",
    Website: "N/A",
    Response: "True",
  },
];
